### ISSUE TITLE
How to Manually Upgrade Comment Mail Pro

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail-kb#3]
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: How to Manually Upgrade Comment Mail Pro
categories: tutorials
tags: installation/upgrading
author: kristineds
github-issue: https://github.com/websharks/comment-mail-kb/issues/3
```
---

In most cases, you can follow the Comment Mail Pro Installation instructions the first time and then configure the Pro Plugin Updater (WordPress Dashboard → Comment Mail → Plugin Updater) to keep Comment Mail Pro updated. However, some web hosts block the Pro Plugin Updater from working correctly, resulting in a 404 error.

If you cannot get your web host to work correctly with the Pro Plugin Updater, or if you have some other scenario that requires you to manually update Comment Mail, then you can follow the instructions below to manually upgrade Comment Mail Pro whenever an update is available.

Step-by-Step: Upgrading ZenCache Pro Manually
1. Log into Comment-Mail.com to download the latest version of Comment Mail Pro.
