### ISSUE TITLE
Can visitors subscribe without commenting?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#30]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Can visitors subscribe without commenting?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/30
```
---

### Commenting Without Subscribing

Yes, visitors can subscribe to any comment without actually commenting. First, please make sure you have enabled the Comment Form Subscribers Options Template. Please see **Dashboard → Comment Mail → Config Options → Comment Form → Enable Comment Form Subscr. Options Template?**.

On the front end, when clicking `Reply`, the **link** to Subscribe without Commenting will be available for all visitors whether logged in or not.

![Subscribe without Commenting](https://cloud.githubusercontent.com/assets/13220018/26276956/fd8b80f2-3db4-11e7-9115-8f356928827c.png)
