### ISSUE TITLE
What version of PHP is required to run Comment Mail?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#33]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: What version of PHP is required to run Comment Mail?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/33
```
---

Comment Mail requires a minimum of PHP 5.4+ to install and run. 

Comment Mail is also compatible with **PHP v7.0**, you must be running PHP v7.0.9+. Starting with Comment Mail v161118, if you're running **PHP v7 < 7.0.9** a warning is displayed in the WordPress Dashboard asking the site owner to upgrade to **PHP v7.0.9** or higher. Note: While **PHP v7.0.9** is adequate, **PHP v7.0.10** is strongly recommended. 

If you are running into issues with PHP Compatibility please open a GitHub issue [here](https://github.com/websharks/comment-mail/issues).
