### ISSUE TITLE
 Does Comment Mail offer support services?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#36]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Does Comment Mail offer support services?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/36
```
---

Comment Mail Pro is sold by WP Sharks™

Please see our [Support Policy](https://wpsharks.com/support-policy) for details.
