### ISSUE TITLE
Are there any recurring fees associated with my purchase of Comment Mail Pro?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#37]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Are there any recurring fees associated with my purchase of Comment Mail Pro?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/37
```
---

No. All versions of Comment Mail Pro are sold with a one-time charge; no recurring fees.

**Lifetime Updates + 12 Months of Support**

A purchase of Comment Mail Pro comes with lifetime plugin updates and access to 12 months (1 year) of support. After 12 months, you may choose to renew your access to support, or not. Renewals do not occur automatically. If you do choose to renew (i.e., you need ongoing access to support) the rate is just $5/year for a Single-Site license, and $10/year for the Unlimited-Site license.
