### ISSUE TITLE
Can I create manual subscriptions for accounts that are already part of my user database?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#39]
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Can I create manual subscriptions for accounts that are already part of my user database?
categories: questions
tags: pre-sales-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/39
```
---

Yes, you would simply need to know their WP User ID#. When viewing your list of Subscribers at **WordPress Dashboard → Comment Mail → Subscriptions**, at the top click **Add New**.

![screen shot 2017-02-17 at 12 57 09 am](https://cloud.githubusercontent.com/assets/13220018/23031485/166d142a-f4ac-11e6-8524-d5a4e0eb9593.png)

This will take you to the "New Subscription" page to fill out the necessary details for the manual subscription.

![screen shot 2017-02-17 at 12 58 37 am](https://cloud.githubusercontent.com/assets/13220018/23031554/59b1f6c4-f4ac-11e6-84f7-285bdcb200b0.png)

This allows you to manually create new subscriptions for existing users.
