### ISSUE TITLE
How to Migrate from Subscribe to Comments Reloaded to Comment Mail (Lite)

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail-kb#4]
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: How to Migrate from Subscribe to Comments Reloaded to Comment Mail (Lite)
categories: tutorials
tags: installation/upgrade
author: kristineds
github-issue: https://github.com/websharks/comment-mail-kb/issues/4
```
---

Article body content here.
