### ISSUE TITLE
Does Comment Mail Integrate with MailChimp?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#41]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Does Comment Mail Integrate with MailChimp?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/41
```
---

Yes, Comment Mail currently supports MailChimp. With MailChimp integrated, when users leave a comment, in addition to subscribing to comment notifications they will also be given the option to subscribe to your site's mailing list. This is a powerful, unobtrusive way of inviting users to join your mailing list as they leave a comment or reply.

![mail chimp](https://user-images.githubusercontent.com/13220018/27347325-d03e0936-5622-11e7-8be7-86ec34f4790b.png)

### MailChimp Subscription on Comment Form

![receive updates](https://user-images.githubusercontent.com/13220018/27347452-340b49f6-5623-11e7-8d9c-f9591217bc23.png)
