### ISSUE TITLE
Comment Form Hook Instructions

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail-kb#9]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Comment Form Hook Instructions
categories: tutorials
tags: comment-form, wordpress-hooks
author: jaswsinc
github-issue: 
```
---

[to be written, see: https://github.com/websharks/comment-mail.com/issues/12]

![2015-06-09_13-47-35](https://cloud.githubusercontent.com/assets/1563559/8070539/78eed178-0eae-11e5-9b8f-1d0dd7418fe7.png)
